services:
  app:
    container_name: ${PROJECT_NAME}-app
    image: ${PROJECT_NAME}-app:dev
    build:
      context: .
    environment:
      ENVIRONMENT: development
      PUID: ${DOCKER_UID:-1000}
      PGID: ${DOCKER_GID:-1000}
      PHP_WORKER_COMMAND: "sleep infinity"
    restart: no
    volumes:
      - .:/var/www/html
      - ./docker/php:/container/custom
    ports:
      - ${DOCKER_PROJECT_IP:-127.0.0.1}:9000:9000
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  php_socket: null
