services:
  app:
    container_name: ${PROJECT_NAME}-app
    image: ${PROJECT_NAME}-app:dev
    build:
      context: .
      target: app_dev
      args:
        - DOCKER_RUNTIME=${DOCKER_RUNTIME:-docker}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_UID=${DOCKER_UID:-1000}
    restart: no
    volumes:
      - php_socket:/var/run/php
      - .:/var/www/html
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    ports:
      - ${DOCKER_PROJECT_IP:-127.0.0.1}:9000:9000
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  php_socket: null
